### ISSUE TITLE
for TASK1: Create a Navigation Bar

### ISSUE THREAD

**Issue by kod-it** [Developer-Student-Club-BIT-Deoghar/Hacktoberfest21#1]

**Comment by CerealNotFound** [comment]
Hey! I want to complete this task!!

**Comment by kod-it** [comment]
> Hey! I want to complete this task!!

Go for it!!

**Comment by CerealNotFound** [comment]
Sir, what links should I add in the navbar ?

**Comment by kod-it** [comment]
> Sir, what links should I add in the navbar ? Otherwise, it's almost complete.

Social Media Links and create a dropbox that redirects to the tools...

**Comment by CerealNotFound** [comment]
Okay sir!

**Comment by CerealNotFound** [comment]
Sir, I have made the pull request for the navbar, please let me know what you think :)
