### ISSUE TITLE
[BUG]: Repetitive team member's name

### ISSUE THREAD

**Issue by guptasajal411** [Developer-Student-Club-BIT-Deoghar/Hacktoberfest21#26]
For Task2
Same member's name are rendered more than 1 time -
![image](https://user-images.githubusercontent.com/70312106/135707533-6ba7fa46-0187-4634-a338-abed5c19aba9.png)
This is because of the `data.json` file, I will shortly create a pull request for fixing this 👍

**Comment by kod-it** [comment]
These are random names... created on temp basis...
I'll be providing u with the exact names... positions and their respective social media links... 
Can u please work on that..?

**Comment by guptasajal411** [comment]
Yes sure! I think you should close **[this](https://github.com/Developer-Student-Club-BIT-Deoghar/Hacktoberfest21/pull/27)** pull request then 🙂
