### ISSUE TITLE
Password Generator For Daily Use Tool

### ISSUE THREAD

**Issue by RahulSahOfficial** [Developer-Student-Club-BIT-Deoghar/Hacktoberfest21#30]
Can i make password generator tool

**Comment by kod-it** [comment]
yaa.. sure go for it!!

**Comment by RahulSahOfficial** [comment]
@dddqwerty @neha030 I was working on it as I got green signal from maintainer @kod-it 
You should ask before starting working on another's issue as all my effort is wasted
