### ISSUE TITLE
for TASK1: Quadratic Equation Solver TOOL

### ISSUE THREAD

**Issue by kod-it** [Developer-Student-Club-BIT-Deoghar/Hacktoberfest21#31]

**Comment by parth-panchal** [comment]
Could you please assign me to this issue? I would love to work on this

**Comment by kod-it** [comment]
> Could you please assign me to this issue? I would love to work on this

Sure!! go for it!!

**Comment by Mark-42-max** [comment]
I would like to work on this issue. Would you like to assign this issue to me?

**Comment by parth-panchal** [comment]
@kod-it the issue has been worked on and I have reopened the pull request after resolving merge conflicts. Please check. Thanks
d
