### ISSUE TITLE
For Task1: I want to add more social medias and redesign the navbar

### ISSUE THREAD

**Issue by SushantPatial** [Developer-Student-Club-BIT-Deoghar/Hacktoberfest21#34]
I'll add social media icons and will try to make the navbar more appealing

**Comment by kod-it** [comment]
Peeps are already working on it... u can try making it more impressive..

**Comment by SushantPatial** [comment]
Sure I'll try

**Comment by SushantPatial** [comment]
@kod-it I created a PR. Please review it
