### ISSUE TITLE
Add active blink to navbar

### ISSUE THREAD

**Issue by Averek7** [Developer-Student-Club-BIT-Deoghar/Hacktoberfest21#62]
Add blink to the link which is active or the link which is being opened

**Comment by Averek7** [comment]
> Hey i would like to contribute to this issue. Can you assign this to me?

Sure, I have made a PR 
You can also

**Comment by Averek7** [comment]
.take

**Comment by iamyogeshmalkani** [comment]
can you elaborate more what i have to do?
