### ISSUE TITLE
for TASK2: Embed image tiles on the TEAM page with links to their social media pages.

### ISSUE THREAD

**Issue by kod-it** [Developer-Student-Club-BIT-Deoghar/Hacktoberfest21#7]
Can refer to https://dsckiet.com/team for inspiration.

**Comment by RiyaGupta89** [comment]
@kod-it May I work on this issue? 
Who will be there on the team page? Only the project maintainers?

**Comment by kod-it** [comment]
> @kod-it May I work on this issue? Who will be there on the team page? Only the project maintainers?

Sure!! 
use random pics on at least 10 image tiles with random names... but don't forget to mention their social media handles... which too can be empty for now...

**Comment by RiyaGupta89** [comment]
@kod-it  Okay.

**Comment by RiyaGupta89** [comment]
@kod-it Can I use some custom css as well?

**Comment by kod-it** [comment]
> @kod-it Can I use some custom css as well?

ofc
